spring.application.name=DemoBaoMat2JPA
spring.datasource.url=jdbc:mysql://localhost:3306/quanly_demo_db
spring.datasource.username=root
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true